Fs=11025;
N=10;
numSamples = 5000;
DownsampleFactor = 15;
frameSize = 10*DownsampleFactor;
hsin = dsp.SineWave( [0.4 1], [10 200], ...
'SamplesPerFrame', frameSize, ...
'SampleRate', Fs);
hlowpass1 = dsp.FIRFilter(...
'Numerator', firpm(20, [0 0.03 0.1 1], [1 1 0 0]));
hts1 = dsp.TimeScope(...
'NumInputPorts', 2, ...
'Name', 'Envelope detection using Amplitude Modulation', ...
'SampleRate', [Fs Fs/DownsampleFactor], ...
'TimeDisplayOffset', [(N/2+frameSize)/Fs 0], ...
'TimeSpanSource', 'Property', ...
'TimeSpan', 0.45, ...
'YLimits', [-2.5 2.5]);
pos = hts1.Position;
for i=1:numSamples/frameSize
sig = step(hsin);
sig = (1+sig(:,1)).*sig(:, 2); 
sigsq = 2*sig.*sig;
sigenv1 = sqrt(step(hlowpass1, downsample(sigsq,...
DownsampleFactor)));
% Plot the signals and envelopes
step(hts1, sig, sigenv1);
end